/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import adt.*;
import entity.*;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CorporateCustomerRegistration extends javax.swing.JFrame {

    customerInt<CorporateCustomer> corCust = new LinkedCustomer();
    customerInt<Customer> cust = new LinkedCustomer();
    staffInt<Staff> staffList = new LinkedStaff();
    ProductListInterface<Product> productList = new ProductLList<>();
    PromoListInterface<Promotion> promoList = new PromoLList<>();
    OrderInterface<Delivery> orderList = new OrderLList<>();
    OrderInterface<PickUp> pickUpList = new OrderLList<>();
    OrderInterface<SalesOrder> salesOrderList = new OrderLList<>();
    
    /**
     * Creates new form CorporateCustomerRegistration
     */
    public CorporateCustomerRegistration() {
        initComponents();
        incrementID();
    }
    
    public CorporateCustomerRegistration(customerInt<Customer> cust,
                                         customerInt<CorporateCustomer> corCust,
                                         staffInt<Staff> staffList,
                                         ProductListInterface<Product> productList,
                                         PromoListInterface<Promotion> promoList,
                                         OrderInterface<Delivery> orderList,
                                         OrderInterface<PickUp> pickUpList,
                                         OrderInterface<SalesOrder> salesOrderList){
        this.cust = cust;
        this.corCust = corCust;
        this.staffList = staffList;
        this.productList = productList;
        this.promoList = promoList;
        this.orderList = orderList;
        this.pickUpList = pickUpList;
        this.salesOrderList = salesOrderList;
        initComponents();
        incrementID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbCompanyName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlbTitle = new javax.swing.JLabel();
        jlbCustomerID = new javax.swing.JLabel();
        jlbConfirmPassword = new javax.swing.JLabel();
        jlbCustomerName = new javax.swing.JLabel();
        jlbContact = new javax.swing.JLabel();
        jlbCorCompName = new javax.swing.JLabel();
        jlbEmail = new javax.swing.JLabel();
        jlbPassword = new javax.swing.JLabel();
        jtfCustomerID = new javax.swing.JTextField();
        jtfCustomerName = new javax.swing.JTextField();
        jtfContact = new javax.swing.JTextField();
        jtfCompanyName = new javax.swing.JTextField();
        jbtRegister = new javax.swing.JButton();
        jbtCancel = new javax.swing.JButton();
        jpfConfirmPass = new javax.swing.JPasswordField();
        jpfPass = new javax.swing.JPasswordField();
        jlblCompanyID = new javax.swing.JLabel();
        jtfCompanyID = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jbBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));

        jlbCompanyName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlbCompanyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCompanyName.setText("Fiore Flowershop");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jlbCompanyName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jlbTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitle.setText("Corporate Customer Registration");

        jlbCustomerID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbCustomerID.setText("Customer ID:");

        jlbConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbConfirmPassword.setText("Confirm Password:");

        jlbCustomerName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbCustomerName.setText("Name:");

        jlbContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbContact.setText("Contact No:");

        jlbCorCompName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbCorCompName.setText("Company Name:");

        jlbEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbEmail.setText("Email:");

        jlbPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbPassword.setText("Password:");

        jtfCustomerID.setEditable(false);
        jtfCustomerID.setFocusable(false);

        jbtRegister.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtRegister.setText("Register");
        jbtRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRegisterActionPerformed(evt);
            }
        });

        jbtCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtCancel.setText("Cancel");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });

        jpfConfirmPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jpfPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jlblCompanyID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblCompanyID.setText("Company ID:");

        jbBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbBack.setText("Back");
        jbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpfPass))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblCompanyID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbCorCompName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbCustomerID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbConfirmPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfCompanyName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfCompanyID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfContact, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfCustomerName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpfConfirmPass)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtfCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jbtRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)))
                .addGap(167, 167, 167))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jbBack)
                .addGap(150, 150, 150)
                .addComponent(jlbTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jlbTitle))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jbBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCompanyID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblCompanyID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbCorCompName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpfConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRegisterActionPerformed
        // TODO add your handling code here:
        if(isNotEmpty()){
            if(isConfirmAdd()){
                if(isPasswordMatch()){
                    registerNew();
                }else{
                    JOptionPane.showMessageDialog(this,"Password and Confirm Password is not match","Not match",JOptionPane.WARNING_MESSAGE);
                    jpfPass.setText("");
                    jpfConfirmPass.setText("");
                }
            }
        }
    }//GEN-LAST:event_jbtRegisterActionPerformed

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        // TODO add your handling code here:
        clearText();
    }//GEN-LAST:event_jbtCancelActionPerformed

    private void jbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBackActionPerformed
        // TODO add your handling code here:
        new LoginPage(cust, corCust, staffList, productList, promoList,orderList,pickUpList,salesOrderList).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbBackActionPerformed

    private void incrementID(){
        jtfCustomerID.setText("CR" + String.format("%04d",corCust.getLength()+1));
        jtfCustomerName.grabFocus();
    }
    
    private boolean isNotEmpty(){
        String emptyTextField = "";
        if(jtfCustomerName.getText().equals("")){
            emptyTextField += "\nCustomer Name";
        }
        if(jtfContact.getText().equals("")){
            emptyTextField += "\nContact Number";
        }
        if(jtfCompanyName.getText().equals("")){
            emptyTextField += "\nCorporate Name";
        }
        if(jtfEmail.getText().equals("")){
            emptyTextField += "\nEmail";
        }
        if(jpfPass.getText().equals("")){
            emptyTextField += "\nPassword";
        }
        if(jpfConfirmPass.getText().equals("")){
            emptyTextField += "\nConfirm Password";
        }
        
        if(!emptyTextField.equals("")){
            JOptionPane.showMessageDialog(this,
                    "The following text field:" + emptyTextField + "\nPlease don't leave it blank",
                    "Please fill in the form",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    
    private String getCustInfo(){
        String info = "";
        info = "Customer Name: " + jtfCustomerName.getText() +
                "\nContact Number: " + jtfContact.getText() +
                "\nCompany Name: " + jtfCompanyName.getText() +
                "\nEmail: " + jtfEmail.getText();
        return info;
    }
    
    private boolean isConfirmAdd(){
        boolean confirm = false;
        int i = JOptionPane.showConfirmDialog(this,getCustInfo() +"\nAre You sure?","Yes or No",JOptionPane.YES_NO_OPTION);
        
        if(i == JOptionPane.YES_OPTION){
            confirm = true;
        }
        
        return confirm;
    }
    
    private boolean isPasswordMatch(){
        boolean match = false;
        String pass = jpfPass.getText();
        String confirmPass = jpfConfirmPass.getText();
        
        if(pass.equals(confirmPass)){
            match = true;
        }
        
        return match;
    }
    
    private CorporateCustomer getCorCust(){
        String custID = jtfCustomerID.getText();
        String name = jtfCustomerName.getText();
        String contact = jtfContact.getText();
        String companyID = jtfCompanyID.getText();
        String companyName = jtfCompanyName.getText();
        String email = jtfEmail.getText();
        String password = jpfPass.getText();
        
        CorporateCustomer newCorCust = new CorporateCustomer(custID,name,contact,password,companyID,companyName,-1,email,-1);
        
        return newCorCust;
    }
    
    private void registerNew(){
        corCust.register(getCorCust());
        JOptionPane.showMessageDialog(this,"Now wait the staff approve your account","Register Success!",JOptionPane.INFORMATION_MESSAGE);
        incrementID();
        clearText();
    }
    
    private void clearText(){
        jtfCustomerName.setText("");
        jtfContact.setText("");
        jtfCompanyID.setText("");
        jtfCompanyName.setText("");
        jtfEmail.setText("");
        jpfPass.setText("");
        jpfConfirmPass.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CorporateCustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CorporateCustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CorporateCustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CorporateCustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CorporateCustomerRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbBack;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtRegister;
    private javax.swing.JLabel jlbCompanyName;
    private javax.swing.JLabel jlbConfirmPassword;
    private javax.swing.JLabel jlbContact;
    private javax.swing.JLabel jlbCorCompName;
    private javax.swing.JLabel jlbCustomerID;
    private javax.swing.JLabel jlbCustomerName;
    private javax.swing.JLabel jlbEmail;
    private javax.swing.JLabel jlbPassword;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JLabel jlblCompanyID;
    private javax.swing.JPasswordField jpfConfirmPass;
    private javax.swing.JPasswordField jpfPass;
    private javax.swing.JTextField jtfCompanyID;
    private javax.swing.JTextField jtfCompanyName;
    private javax.swing.JTextField jtfContact;
    private javax.swing.JTextField jtfCustomerID;
    private javax.swing.JTextField jtfCustomerName;
    private javax.swing.JTextField jtfEmail;
    // End of variables declaration//GEN-END:variables
}
