/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import adt.*;
import entity.*;
/**
 *
 * @author jitpe
 */
public class DeliveryOrder extends javax.swing.JFrame {
    customerInt<CorporateCustomer> corCust = new LinkedCustomer();
    customerInt<Customer> cust = new LinkedCustomer();
    staffInt<Staff> staffList = new LinkedStaff();
    ProductListInterface<Product> productList = new ProductLList<>();
    PromoListInterface<Promotion> promoList = new PromoLList<>();
    OrderInterface<Delivery> orderList = new OrderLList<>();
    OrderInterface<PickUp> pickUpList = new OrderLList<>();
    OrderInterface<SalesOrder> salesOrderList = new OrderLList<>();
    
    Customer currentCust = new Customer();
    Product product = new Product();
    /**
     * Creates new form AddOrder
     */
    public DeliveryOrder() {
        initComponents();
        addRowToTable();
        retrieveProdID();
        incrementID();
    }
    
    public DeliveryOrder(Customer currentCust,
                         customerInt<Customer> cust,
                         customerInt<CorporateCustomer> corCust,
                         staffInt<Staff> staffList,
                         ProductListInterface<Product> productList,
                         PromoListInterface<Promotion> promoList,
                         OrderInterface<Delivery> orderList,
                         OrderInterface<PickUp> pickUpList,
                         OrderInterface<SalesOrder> salesOrderList){
        this.currentCust = currentCust;
        this.cust = cust;
        this.corCust = corCust;
        this.staffList = staffList;
        this.productList = productList;
        this.promoList = promoList;
        this.orderList = orderList;
        this.pickUpList = pickUpList;
        this.salesOrderList = salesOrderList;
        initComponents();
        addRowToTable();
        retrieveProdID();
        incrementID();
    }
    
    public void addRowToTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        Object rowData[] = new Object[6];
        
        for(int i=0; i<productList.getNumberOfEntries(); i++){
            rowData[0] = productList.getEntry(i+1).getId();
            rowData[1] = productList.getEntry(i+1).getName();
            rowData[2] = productList.getEntry(i+1).getProductType();
            rowData[3] = productList.getEntry(i+1).getProductDesc();
            rowData[4] = productList.getEntry(i+1).getPrice();
            rowData[5] = productList.getEntry(i+1).getQuantity();
            
            model.addRow(rowData);
        }
    }
    
    private void clearText(){
        //jtfID.setText("");
        jcbProdID.setSelectedIndex(0);
        jtfQuantity.setText("");
        jtfTotal.setText("");
        jtaAddress.setText("");
        jtfPostCode.setText("");
        jcbCity.setSelectedIndex(0);
        jtfDate.setText("");
        //jtfID.requestFocus();
    }
    
    public void retrieveProdID(){
       
        for(int i = 0; i < productList.getNumberOfEntries(); i++){
            String prod = productList.getEntry(i + 1).getId();
            jcbProdID.addItem("" + (prod));
        }
        
    }
    
    private void incrementID(){
        jtfID.setText("DO" + String.format("%04d",orderList.getNumberOfEntries()+1));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfID = new javax.swing.JTextField();
        jtfQuantity = new javax.swing.JTextField();
        jbtConfirm = new javax.swing.JButton();
        jtfCancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaAddress = new javax.swing.JTextArea();
        jtfTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtfPostCode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcbCity = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jcbProdID = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jtfDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fiore Flowershop");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Product Type", "Description", "Price(RM)", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText(" ID                     :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText(" Quantity             :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText(" Total(RM)           :");

        jtfID.setEditable(false);
        jtfID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIDActionPerformed(evt);
            }
        });

        jtfQuantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfQuantityActionPerformed(evt);
            }
        });

        jbtConfirm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtConfirm.setText("Confirm");
        jbtConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConfirmActionPerformed(evt);
            }
        });

        jtfCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfCancel.setText("Cancel");
        jtfCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCancelActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText(" Address              :");

        jtaAddress.setColumns(20);
        jtaAddress.setRows(5);
        jScrollPane2.setViewportView(jtaAddress);

        jtfTotal.setEditable(false);
        jtfTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTotalActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Add to Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText(" PostCode            :");

        jtfPostCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText(" City                   :");

        jcbCity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cheras", "Setapak", "Klang" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText(" Product ID          :");

        jcbProdID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText(" Delivery Date       :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfDate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbProdID, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfPostCode, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jbtConfirm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addComponent(jtfCancel))
                            .addComponent(jcbCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfQuantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(jtfTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbProdID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbCity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(jtfDate))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtConfirm)
                    .addComponent(jtfCancel))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIDActionPerformed

    private void jbtConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConfirmActionPerformed
        // TODO add your handling code here:
        new CustomerHomepage(currentCust,cust, corCust, staffList, productList, promoList,orderList,pickUpList,salesOrderList).setVisible(true);
        this.setVisible(false);
        
        
//        if(jtfID.getText().equals("") && jtfQuantity.getText().equals("") && jtfDate.getText().equals("") && jtfTime.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - ID\n - Quantity\n - Date\n - Time", "ERROR!", JOptionPane.ERROR_MESSAGE);
//        }
//        else if(!jtfID.getText().equals("") && jtfQuantity.getText().equals("") && jtfDate.getText().equals("") && jtfTime.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - Quantity\n - Date\n - Time", "ERROR!", JOptionPane.ERROR_MESSAGE);
//        }
//        else if(jtfID.getText().equals("") && !jtfQuantity.getText().equals("") && jtfDate.getText().equals("") && jtfTime.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - ID\n - Date\n - Time", "ERROR!", JOptionPane.ERROR_MESSAGE);
//        }
//        else if(jtfID.getText().equals("") && jtfQuantity.getText().equals("") && !jtfDate.getText().equals("") && jtfTime.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - ID\n - Quantity\n - Time", "ERROR!", JOptionPane.ERROR_MESSAGE);
//        }
//        else if(jtfID.getText().equals("") && jtfQuantity.getText().equals("") && jtfDate.getText().equals("") && !jtfTime.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - ID\n - Quantity\n - Date", "ERROR!", JOptionPane.ERROR_MESSAGE);
//        }
//        else if(!jtfID.getText().equals("") && !jtfQuantity.getText().equals("") && jtfDate.getText().equals("") && jtfTime.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - Date\n - Time", "ERROR!", JOptionPane.ERROR_MESSAGE);
//        }
//        else if(!jtfID.getText().equals("") && jtfQuantity.getText().equals("") && !jtfDate.getText().equals("") && jtfTime.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - Quantity\n - Time", "ERROR!", JOptionPane.ERROR_MESSAGE);
//        }
//        else if(!jtfID.getText().equals("") && jtfQuantity.getText().equals("") && jtfDate.getText().equals("") && !jtfTime.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - Quantity\n - Date", "ERROR!", JOptionPane.ERROR_MESSAGE);
//        }
//        else if(!jtfID.getText().equals("") && !jtfQuantity.getText().equals("") && !jtfDate.getText().equals("") && jtfTime.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - Time", "ERROR!", JOptionPane.ERROR_MESSAGE);
//        }
//        else if(!jtfID.getText().equals("") && !jtfQuantity.getText().equals("") && jtfDate.getText().equals("") && !jtfTime.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - Date", "ERROR!", JOptionPane.ERROR_MESSAGE);
//        }
//        else{
//            if(jtfID.getText().equals("FR0000") || jtfID.getText().equals("FA0001") || jtfID.getText().equals("FB0002") || jtfID.getText().equals("FK0003")){
//                JOptionPane.showMessageDialog(null, "Order success!", "SUCCESS!", JOptionPane.INFORMATION_MESSAGE);
//                
//            }
//            else{
//                JOptionPane.showMessageDialog(null, "ID not match", "ERROR", JOptionPane.ERROR_MESSAGE);
//            }
//        }
    }//GEN-LAST:event_jbtConfirmActionPerformed

    private boolean checkEmpty(){
        String msg = "";
        if(jtfQuantity.getText().equals("")){
            msg += "\nQuantity";
        }
        if(jtaAddress.getText().equals("")){
            msg += "\nAddress";
        }
        if(jtfPostCode.getText().equals("")){
            msg += "\nPostCode";
        }
        if(jtfDate.getText().equals("")){
            msg += "\nDelivery Date";
        }
        
        if(!msg.equals("")){
            JOptionPane.showMessageDialog(null, "The fill in the following text field!"+ msg, "Please fill in the form completely", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        return true;
    }
    
    private void jtfCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCancelActionPerformed
        // TODO add your handling code here:
        clearText();
    }//GEN-LAST:event_jtfCancelActionPerformed

    private void jtfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(checkEmpty()){
            int yesno = JOptionPane.showConfirmDialog(null, "Do you want to add the order?", "ARE YOU SURE???", JOptionPane.YES_NO_OPTION);
                if(yesno == JOptionPane.YES_OPTION){
                    product.setId(jcbProdID.getSelectedItem().toString());
                    Delivery newOrder = new Delivery(jtfID.getText(), product, Integer.parseInt(jtfQuantity.getText()), Double.parseDouble(jtfTotal.getText()), currentCust, "Unpaid", jtaAddress.getText(), Integer.parseInt(jtfPostCode.getText()), jcbCity.getSelectedItem().toString(), jtfDate.getText());
                    orderList.add(newOrder);
                    incrementID();
                }
        }
        for(int i=0; i<orderList.getNumberOfEntries(); i++){
            String s = "\nOrder ID: "+ orderList.getEntry(i+1).getOrderID()+ "\nProduct ID: "+ orderList.getEntry(i+1).getProduct().getId()+ "\nQuantity: "+ orderList.getEntry(i+1).getQuantity()+ "\nTotal Price(RM): "+ orderList.getEntry(i+1).getTotalPrice()+ "\nAddress: "+ orderList.getEntry(i+1).getAddress()+ "\nPostCode: "+ orderList.getEntry(i+1).getPostCode()+ "\nCity: "+ orderList.getEntry(i+1).getCity()+ "\nDelivery Date: "+ orderList.getEntry(i+1).getDate()+ "\n";
            JOptionPane.showMessageDialog(null, s, "HELLO WORLD!", JOptionPane.INFORMATION_MESSAGE);
            break;
        }
        clearText();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new CustomerHomepage(currentCust,cust, corCust, staffList, productList, promoList,orderList,pickUpList,salesOrderList).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtfQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfQuantityActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<productList.getNumberOfEntries(); i++){
            String selectedProdID = jcbProdID.getSelectedItem().toString();
            if(selectedProdID.equals(productList.getEntry(i+1).getId())){
                double price = productList.getEntry(i+1).getPrice();
                double needQty = Double.parseDouble(jtfQuantity.getText());
                if(needQty >= 0 && needQty <= productList.getEntry(i+1).getQuantity()){
                    double total = price * needQty;
                    jtfTotal.setText("" + total);
                }else{
                    JOptionPane.showMessageDialog(this,"The quantity you need is exceed the available quantity","Exceed Quantty", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jtfQuantityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtConfirm;
    private javax.swing.JComboBox<String> jcbCity;
    private javax.swing.JComboBox<String> jcbProdID;
    private javax.swing.JTextArea jtaAddress;
    private javax.swing.JButton jtfCancel;
    private javax.swing.JTextField jtfDate;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfPostCode;
    private javax.swing.JTextField jtfQuantity;
    private javax.swing.JTextField jtfTotal;
    // End of variables declaration//GEN-END:variables
}
