package test;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import entity.*;
import adt.*;

/**
 *
 * @author ASUS
 */
public class StaffAddProduct extends javax.swing.JFrame {
    
    customerInt<CorporateCustomer> corCust = new LinkedCustomer();
    customerInt<Customer> cust = new LinkedCustomer();
    staffInt<Staff> staffList = new LinkedStaff();
    ProductListInterface<Product> productList = new ProductLList<>();
    PromoListInterface<Promotion> promoList = new PromoLList<>();
    OrderInterface<Delivery> orderList = new OrderLList<>();
    OrderInterface<PickUp> pickUpList = new OrderLList<>();
    OrderInterface<SalesOrder> salesOrderList = new OrderLList<>();
    ManageOrderInterface<PickUp> manageOrderList = new ManageOrderList<>();
    ManageOrderInterface<Delivery> manageDeliveryList = new ManageOrderList<>();
    
    Staff currentStaff = new Staff();
    
    /**
     * Creates new form StaffAddProduct
     */
    public StaffAddProduct() {
        initComponents();
        StoreData();
        incrementId();
        RefreshTable();
    }
    
    public StaffAddProduct(Staff currentStaff,
                           customerInt<Customer> cust,
                           customerInt<CorporateCustomer> corCust,
                           staffInt<Staff> staffList,
                           ProductListInterface<Product> productList,
                           PromoListInterface<Promotion> promoList,
                           OrderInterface<Delivery> orderList,
                           OrderInterface<PickUp> pickUpList,
                           OrderInterface<SalesOrder> salesOrderList,
                           ManageOrderInterface<PickUp> manageOrderList,
                           ManageOrderInterface<Delivery> manageDeliveryList) {
        this.currentStaff = currentStaff;
        this.cust = cust;
        this.corCust = corCust;
        this.staffList = staffList;
        this.productList = productList;
        this.promoList = promoList;
        this.orderList = orderList;
        this.pickUpList = pickUpList;
        this.salesOrderList = salesOrderList;
        this.manageOrderList = manageOrderList;
        this.manageDeliveryList = manageDeliveryList;
        initComponents();
        incrementId();
        RefreshTable();
    }
    
    public void StoreData(){
       productList.addProd(new Product("P001","Rose","Fresh Flowers","Collect on current day morning 100% pure and fresh",50.0,5));
       productList.addProd(new Product("P002","Sun Flowers","Fresh Flowers","Collect on current day morning 100% pure and fresh",10.0,2));
       productList.addProd(new Product("P003","Moon Flowers","Fresh Flowers","Collect on current day morning 100% pure and fresh",10.0,2));
    }
  
     public void RefreshTable(){
        DefaultTableModel model = (DefaultTableModel) jtbProduct.getModel();
        int countRow = model.getRowCount();
        for(int j = countRow-1;j>=0;j--){
            model.removeRow(j);
        }
        
        for(int i=0; i <productList.getNumberOfEntries();i++){
            model.addRow(new Object[]{
           productList.getEntry(i+1).getId(),
           productList.getEntry(i+1).getName(),
           productList.getEntry(i+1).getProductType(),
           productList.getEntry(i+1).getProductDesc(),
           productList.getEntry(i+1).getPrice(),
           productList.getEntry(i+1).getQuantity()
            });
        }
    }

     public void incrementId(){
        if(!productList.isEmpty()){
            String id = productList.getLastItem().getId();
            int i = Integer.parseInt(id.substring(1));
            jtfProductID.setText("P" + String.format("%03d",i+1));
        }else{
            jtfProductID.setText("P" + String.format("%03d",1));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblStaffID = new javax.swing.JLabel();
        jtfStaffID = new javax.swing.JTextField();
        lblProductID = new javax.swing.JLabel();
        jtfProductID = new javax.swing.JTextField();
        lblProductName = new javax.swing.JLabel();
        jtfProductName = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        jtfPrice = new javax.swing.JTextField();
        jtfRM = new javax.swing.JTextField();
        lblQuan = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaDesc = new javax.swing.JTextArea();
        jtfQuan = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jbtAdd = new javax.swing.JButton();
        lblCatog = new javax.swing.JLabel();
        jcbProductType = new javax.swing.JComboBox<>();
        jbtBack = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbProduct = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Fiore Flowershop");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("CompName");

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        lblStaffID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblStaffID.setText("Staff ID :");

        jtfStaffID.setEditable(false);
        jtfStaffID.setBackground(new java.awt.Color(255, 255, 255));
        jtfStaffID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfStaffID.setForeground(new java.awt.Color(102, 102, 102));
        jtfStaffID.setText("S1001");
        jtfStaffID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblProductID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblProductID.setText("Product ID :");

        jtfProductID.setEditable(false);
        jtfProductID.setBackground(new java.awt.Color(255, 255, 255));
        jtfProductID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfProductID.setForeground(new java.awt.Color(102, 102, 102));
        jtfProductID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtfProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfProductIDActionPerformed(evt);
            }
        });

        lblProductName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblProductName.setText("Product Name :");

        jtfProductName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfProductName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPrice.setText("Price (per) :");

        jtfPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfPrice.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtfPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPriceActionPerformed(evt);
            }
        });

        jtfRM.setBackground(new java.awt.Color(153, 153, 255));
        jtfRM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfRM.setText("RM");
        jtfRM.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblQuan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblQuan.setText("Quantitie(s) :");

        lblDesc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDesc.setText("Product Description :");

        jtaDesc.setColumns(20);
        jtaDesc.setRows(5);
        jScrollPane2.setViewportView(jtaDesc);

        jtfQuan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfQuan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtfQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfQuanActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jbtAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtAdd.setText("Add Product");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });

        lblCatog.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCatog.setText("Product Type :");

        jcbProductType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbProductType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fresh Flowers", "Bouquets", "Floral Arrangements" }));
        jcbProductType.setToolTipText("");

        jbtBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtBack.setText("Back");
        jbtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblProductName)
                                .addComponent(lblProductID)
                                .addComponent(lblStaffID)
                                .addComponent(jtfStaffID)
                                .addComponent(jtfProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jtfRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jbtBack)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblQuan)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblDesc)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jtfQuan, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblPrice))))
                                        .addGap(32, 32, 32)))
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(129, 129, 129))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfProductName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCatog, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbProductType, javax.swing.GroupLayout.Alignment.LEADING, 0, 202, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jbtAdd)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStaffID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblProductID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblProductName)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jtfProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(lblCatog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbProductType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDesc)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblPrice)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(lblQuan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jbtBack)
                        .addGap(55, 55, 55)
                        .addComponent(jbtAdd)
                        .addGap(42, 42, 42))))
        );

        lblStaffID.getAccessibleContext().setAccessibleName("lblStaffID");
        jtfStaffID.getAccessibleContext().setAccessibleName("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtbProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Product Type", "Product Desc", "Price(RM)", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbProduct);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(220, 220, 220))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfProductIDActionPerformed

    private void jtfPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPriceActionPerformed

    private void jtfQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfQuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfQuanActionPerformed

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
       if(!isEmpty()){
            addNewProduct();
            incrementId();
            RefreshTable();
            clearText();
        }
    }//GEN-LAST:event_jbtAddActionPerformed

    
    
    private void jbtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBackActionPerformed
        // TODO add your handling code here:
        new Homepage(currentStaff, cust, corCust, staffList, productList, promoList,orderList,pickUpList,salesOrderList, manageOrderList, manageDeliveryList).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtBackActionPerformed

    public void addNewProduct(){
        String ProdID = jtfProductID.getText();
        String PName = jtfProductName.getText();
        String PDesc = jtaDesc.getText();
        String PType = jcbProductType.getSelectedItem().toString();
        Double PPrice = Double.parseDouble(jtfPrice.getText());
        int PQuan = Integer.parseInt(jtfQuan.getText());
            
        productList.addProd(new Product(ProdID,PName,PType,PDesc,PPrice,PQuan));
    }
    
    public void clearText(){
        jtfProductName.setText("");
        jtaDesc.setText("");
        jtfPrice.setText("");
        jtfQuan.setText("");
    }
    
    public boolean isEmpty(){
        boolean empty = true;
        
        if(jtfProductName.getText().equals("") && jtaDesc.getText().equals("") && jtfPrice.getText().equals("") && jtfQuan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"The below field(s) can't be empty \n"
                    + "Product Name \n Product Description \n Price \n Quantity \n","Error",JOptionPane.ERROR_MESSAGE);
        }else if(!jtfProductName.getText().equals("") && jtaDesc.getText().equals("") && jtfPrice.getText().equals("") && jtfQuan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"The below field(s) can't be empty \n"
                    + "Product Description \n Price \n Quantity \n","Error",JOptionPane.ERROR_MESSAGE);
        }else if(!jtfProductName.getText().equals("") && !jtaDesc.getText().equals("") && jtfPrice.toString()=="" && jtfQuan.toString()==""){
            JOptionPane.showMessageDialog(null,"The below field(s) can't be empty \n"
                    + "Price \n Quantity \n","Error",JOptionPane.ERROR_MESSAGE);
        }else if(!jtfProductName.getText().equals("") && !jtaDesc.getText().equals("") && !jtfPrice.toString().equals("") && jtfQuan.toString()==""){
            JOptionPane.showMessageDialog(null,"The below field(s) can't be empty \n"
                    + "Quantity \n","Error",JOptionPane.ERROR_MESSAGE);
        }else if(jtfProductName.getText().equals("") && jtaDesc.getText().equals("") && !jtfPrice.toString().equals("") && !jtfQuan.toString().equals("")){
            JOptionPane.showMessageDialog(null,"The below field(s) can't be empty \n"
                    + "Product Name \n Product Description","Error",JOptionPane.ERROR_MESSAGE);
        }else if(jtfProductName.getText().equals("") && !jtaDesc.getText().equals("") && jtfPrice.getText().equals("") && !jtfQuan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"The below field(s) can't be empty \n"
                    + "Product Name \nPrice ","Error",JOptionPane.ERROR_MESSAGE);
        }else if(jtfProductName.getText().equals("") && !jtaDesc.getText().equals("") && !jtfPrice.getText().equals("") && jtfQuan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"The below field(s) can't be empty \n"
                    + "Product Name \n  Quantity \n","Error",JOptionPane.ERROR_MESSAGE);
        }else if(!jtfProductName.getText().equals("") && jtaDesc.getText().equals("") && jtfPrice.getText().equals("") && !jtfQuan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"The below field(s) can't be empty \n"
                    + "Product Description \n Price\n","Error",JOptionPane.ERROR_MESSAGE);
        }else if(!jtfProductName.getText().equals("") && jtaDesc.getText().equals("") && !jtfPrice.getText().equals("") && jtfQuan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"The below field(s) can't be empty \n"
                    + "Product Description \nQuantity \n","Error",JOptionPane.ERROR_MESSAGE);
        }else if(!jtfProductName.getText().equals("") && !jtaDesc.getText().equals("") && jtfPrice.getText().equals("") && jtfQuan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"The below field(s) can't be empty \n"
                    + "Price \n Quantity \n","Error",JOptionPane.ERROR_MESSAGE);
        }else if(!jtfProductName.getText().equals("") && !jtaDesc.getText().equals("") && jtfPrice.getText().equals("") && !jtfQuan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"The below field(s) can't be empty \n"
                    + "Price\n","Error",JOptionPane.ERROR_MESSAGE);
        }else if(!jtfProductName.getText().equals("") && jtaDesc.getText().equals("") && !jtfPrice.getText().equals("") && !jtfQuan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"The below field(s) can't be empty \n"
                    + "Product Description\n","Error",JOptionPane.ERROR_MESSAGE);
        }else if(jtfProductName.getText().equals("") && !jtaDesc.getText().equals("") && !jtfPrice.getText().equals("") && !jtfQuan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"The below field(s) can't be empty \n"
                    + "Product Name\n","Error",JOptionPane.ERROR_MESSAGE);
        }else if(jtfProductName.getText().equals("") && jtaDesc.getText().equals("") && !jtfPrice.getText().equals("") && jtfQuan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"The below field(s) can't be empty \n"
                    + "Product Name \n Product Description\n Quantity \n","Error",JOptionPane.ERROR_MESSAGE);
        }else if(jtfProductName.getText().equals("") && !jtaDesc.getText().equals("") && jtfPrice.getText().equals("") && jtfQuan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"The below field(s) can't be empty \n"
                    + "Product Name \n Price \n Quantity \n","Error",JOptionPane.ERROR_MESSAGE);
        }else if(jtfProductName.getText().equals("") && jtaDesc.getText().equals("") && jtfPrice.getText().equals("") && !jtfQuan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"The below field(s) can't be empty \n"
                    + "Product Name \n Product Description \n Price \n","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            empty = false;
        }
        return empty;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffAddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtBack;
    private javax.swing.JComboBox<String> jcbProductType;
    private javax.swing.JTextArea jtaDesc;
    private javax.swing.JTable jtbProduct;
    private javax.swing.JTextField jtfPrice;
    private javax.swing.JTextField jtfProductID;
    private javax.swing.JTextField jtfProductName;
    private javax.swing.JTextField jtfQuan;
    private javax.swing.JTextField jtfRM;
    private javax.swing.JTextField jtfStaffID;
    private javax.swing.JLabel lblCatog;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProductID;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblQuan;
    private javax.swing.JLabel lblStaffID;
    // End of variables declaration//GEN-END:variables
}
