package test;




import entity.*;
import adt.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import adt.PromoListInterface;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class StaffManagePromotion extends javax.swing.JFrame {
    
    customerInt<CorporateCustomer> corCust = new LinkedCustomer();
    customerInt<Customer> cust = new LinkedCustomer();
    staffInt<Staff> staffList = new LinkedStaff();
    ProductListInterface<Product> productList = new ProductLList<>();
    PromoListInterface<Promotion> promoList = new PromoLList<>();
    OrderInterface<Delivery> orderList = new OrderLList<>();
    OrderInterface<PickUp> pickUpList = new OrderLList<>();
    OrderInterface<SalesOrder> salesOrderList = new OrderLList<>();
    ManageOrderInterface<PickUp> manageOrderList = new ManageOrderList<>();
    ManageOrderInterface<Delivery> manageDeliveryList = new ManageOrderList<>();
    
    Staff currentStaff = new Staff();
    
    /**
     * Creates new form StaffCreatePromotion
     */
    public StaffManagePromotion() {
       initComponents();
       StoreData();
       incrementId();
       RefreshTable();
    }
    
    public StaffManagePromotion(Staff currentStaff,
                                customerInt<Customer> cust,
                                customerInt<CorporateCustomer> corCust,
                                staffInt<Staff> staffList,
                                ProductListInterface<Product> productList,
                                PromoListInterface<Promotion> promoList,
                                OrderInterface<Delivery> orderList,
                                OrderInterface<PickUp> pickUpList,
                                OrderInterface<SalesOrder> salesOrderList,
                                ManageOrderInterface<PickUp> manageOrderList,
                                ManageOrderInterface<Delivery> manageDeliveryList) {
        this.currentStaff = currentStaff;
        this.cust = cust;
        this.corCust = corCust;
        this.staffList = staffList;
        this.productList = productList;
        this.promoList = promoList;
        this.orderList = orderList;
        this.pickUpList = pickUpList;
        this.salesOrderList = salesOrderList;
        this.manageOrderList = manageOrderList;
        this.manageDeliveryList = manageDeliveryList;
        initComponents();
        incrementId();
        RefreshTable();
    }
    
    
     public void RefreshTable(){
        DefaultTableModel model = (DefaultTableModel) jtbPromotion.getModel();
        int countRow = model.getRowCount();
        for(int j = countRow-1;j>=0;j--){
            model.removeRow(j);
        }
        
        for(int i=0; i <promoList.getNumberOfEntries();i++){
            model.addRow(new Object[]{
            promoList.getEntry(i+1).getId(),
            promoList.getEntry(i+1).getName(),
            promoList.getEntry(i+1).getPromotionType(),
            promoList.getEntry(i+1).getPromotionDesc()});
        }
    }
     
     public void StoreData(){
    promoList.addPromo(new Promotion("PM001","Lucky November","Fresh Flowers","buy more than 3 items and show to staff at counter to get a free fresh flower"));
       promoList.addPromo(new Promotion("PM002","Lucky Sunday","Fresh Flowers","buy more than 3 items and show to staff at counter to get a free fresh flower"));
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblStaffID = new javax.swing.JLabel();
        jtfStaffID = new javax.swing.JTextField();
        lblPromoID = new javax.swing.JLabel();
        lblPromoName = new javax.swing.JLabel();
        jtfPromoName = new javax.swing.JTextField();
        lblDesc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaDesc = new javax.swing.JTextArea();
        jSeparator5 = new javax.swing.JSeparator();
        jbtDelete = new javax.swing.JButton();
        lblProductType = new javax.swing.JLabel();
        jtfProductType = new javax.swing.JTextField();
        jtfPromoID = new javax.swing.JTextField();
        jbtAdd = new javax.swing.JButton();
        jbtBack = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbPromotion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Fiore Flowershop");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        lblStaffID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblStaffID.setText("Staff ID :");

        jtfStaffID.setEditable(false);
        jtfStaffID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfStaffID.setForeground(new java.awt.Color(102, 102, 102));
        jtfStaffID.setText("S1001");
        jtfStaffID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblPromoID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPromoID.setText("Promotion ID :");

        lblPromoName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPromoName.setText("Promotion Name :");

        jtfPromoName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfPromoName.setForeground(new java.awt.Color(102, 102, 102));
        jtfPromoName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblDesc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDesc.setText("Promotion Description :");

        jtaDesc.setColumns(20);
        jtaDesc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtaDesc.setForeground(new java.awt.Color(102, 102, 102));
        jtaDesc.setRows(5);
        jScrollPane2.setViewportView(jtaDesc);

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jbtDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtDelete.setText("Delete Promotion");
        jbtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDeleteActionPerformed(evt);
            }
        });

        lblProductType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblProductType.setText("Product Type :");

        jtfProductType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfProductType.setForeground(new java.awt.Color(102, 102, 102));

        jtfPromoID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfPromoID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtfPromoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPromoIDActionPerformed(evt);
            }
        });

        jbtAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtAdd.setText("Add Promotion");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });

        jbtBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtBack.setText("Back");
        jbtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblPromoName)
                                .addComponent(lblPromoID)
                                .addComponent(lblStaffID)
                                .addComponent(jtfStaffID))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDesc))
                                .addGap(32, 32, 32)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(129, 129, 129))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfPromoName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductType, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtfProductType, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtfPromoID, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtBack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStaffID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lblPromoID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPromoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblPromoName)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jtfPromoName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(lblProductType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfProductType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDesc)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jbtBack)
                        .addGap(18, 18, 18)
                        .addComponent(jbtAdd)
                        .addGap(45, 45, 45)
                        .addComponent(jbtDelete)
                        .addGap(69, 69, 69))))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtbPromotion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Promotion ID", "Promotion Name", "Product Type", "Promotion Desc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbPromotion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbPromotionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbPromotion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(232, 232, 232))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDeleteActionPerformed
        for(int i =0;i< promoList.getNumberOfEntries();i++){
            
            if(jtfPromoID.getText().equals(promoList.getEntry(i+1).id)){
                promoList.removePromo(i+1);
                
                
            }
            
        }
        RefreshTable();
        jtfPromoID.setText("");
        jtfPromoName.setText("");
        jtfProductType.setText("");
        jtaDesc.setText("");
        
    }//GEN-LAST:event_jbtDeleteActionPerformed

    private void jtbPromotionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbPromotionMouseClicked
        
        int selectedRow = jtbPromotion.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jtbPromotion.getModel();
        jtfPromoID.setText(model.getValueAt(selectedRow,0).toString());
        jtfPromoName.setText(model.getValueAt(selectedRow,1).toString());
        jtfProductType.setText(model.getValueAt(selectedRow,2).toString());
        jtaDesc.setText(model.getValueAt(selectedRow,3).toString());
        
    }//GEN-LAST:event_jtbPromotionMouseClicked

    private void jtfPromoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPromoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPromoIDActionPerformed

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
    String PID = jtfPromoID.getText();
    String PName = jtfPromoName.getText();
    String PType = jtfProductType.getText();
    String PDesc = jtaDesc.getText();
    
    
    promoList.addPromo(new Promotion(PID,PName,PType,PDesc));
    incrementId();
    RefreshTable();
        
        jtfPromoName.setText("");
        jtfProductType.setText("");
        jtaDesc.setText("");
   
    }//GEN-LAST:event_jbtAddActionPerformed

    public void incrementId(){
        if(!promoList.isEmpty()){
        String id = promoList.getLastItem().getId();
        int i = Integer.parseInt(id.substring(2));
        
        jtfPromoID.setText("PM" + String.format("%03d",i+1));
        }else{
            jtfPromoID.setText("PM" + String.format("%03d",1));
        }
    }
    private void jbtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBackActionPerformed
        // TODO add your handling code here:
        new Homepage(currentStaff, cust, corCust, staffList, productList, promoList,orderList,pickUpList,salesOrderList, manageOrderList, manageDeliveryList).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtBackActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffManagePromotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffManagePromotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffManagePromotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffManagePromotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffManagePromotion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtBack;
    private javax.swing.JButton jbtDelete;
    private javax.swing.JTextArea jtaDesc;
    private javax.swing.JTable jtbPromotion;
    private javax.swing.JTextField jtfProductType;
    private javax.swing.JTextField jtfPromoID;
    private javax.swing.JTextField jtfPromoName;
    private javax.swing.JTextField jtfStaffID;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblProductType;
    private javax.swing.JLabel lblPromoID;
    private javax.swing.JLabel lblPromoName;
    private javax.swing.JLabel lblStaffID;
    // End of variables declaration//GEN-END:variables
}
